#
# Docker Workshop
# Chat App Backend
# Dockerfile
#

FROM node:22-alpine AS base

# create and set the working directory
WORKDIR /app
# copy package.json and package-lock.json
COPY package*.json ./
# install dependencies
RUN npm ci
# copy the rest of the application code
COPY . .
# build the application
RUN npm run build

# container entrypoint
ENV NODE_ENV=production
CMD ["node", "dist/index.js"]
